language: php
php: 7.3
before_install:
- openssl aes-256-cbc -K $encrypted_bdcf97989f60_key -iv $encrypted_bdcf97989f60_iv
  -in deploy_key.enc -out deploy_key -d
install:
- npm install
- npm install -g jscs
- npm install -g jshint
- wget https://develop.svn.wordpress.org/trunk/.jshintrc
before_script:
- find . \( -name '*.php' \) -exec php -lf {} \;
- jshint .
- jscs .
script:
- echo 'testing...'
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $SERVER_USER@$SERVER_IP_ADDRESS pwd
