language: php
php: 7.3
before_install:
- openssl aes-256-cbc -K $encrypted_bdcf97989f60_key -iv $encrypted_bdcf97989f60_iv
  -in deploy_key.enc -out deploy_key -d
install:
- npm install
script:
- echo 'testing...'
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -t $SERVER_USER@$SERVER_IP_ADDRESS "mkdir -p /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/macarena-portfolio-theme"
- rsync -avr --exclude='deploy_key' --exclude='.git' . $SERVER_USER@$SERVER_IP_ADDRESS:/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/macarena-portfolio-theme/
